# Generated by Django 3.0.6 on 2020-05-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requester_invite_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requester',
            name='shoppers',
        ),
        migrations.AddField(
            model_name='requester',
            name='shoppers',
            field=models.ManyToManyField(blank=True, null=True, related_name='requesters', to='core.Shopper'),
        ),
    ]
