# Generated by Django 3.0.6 on 2020-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200527_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteditem',
            name='claimed_epoch_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
