# Generated by Django 3.0.6 on 2020-05-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_requested_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
